image:
  repository: hanifshaker/gitops-pipeline
  tag: 3f28e3f
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false
httpRoute:
  enabled: false